"""
Modern weblog template system for EVLA pipeline.

Pure Python implementation using string.Template - zero dependencies.
"""

from datetime import datetime
from string import Template
from typing import Any, Dict


class WeblogTemplateEngine:
    """Simple template engine using Python's built-in string.Template."""

    def __init__(self):
        self.templates = {}
        self._load_templates()

    def _load_templates(self):
        """Load all template definitions."""

        # Base HTML template with modern structure
        self.templates["base"] = Template(
            """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>$title - EVLA Pipeline Report</title>
    <style>$css_content</style>
</head>
<body>
    <header class="pipeline-header">
        <h1>EVLA Pipeline Report</h1>
        <nav class="main-nav">$navigation</nav>
    </header>
    <main class="content">$content</main>
    <footer class="pipeline-footer">
        <p>Generated by EVLA Pipeline v$pipeline_version on $generation_date</p>
    </footer>
    <script>$js_content</script>
</body>
</html>"""
        )

        # Navigation template
        self.templates["navigation"] = Template(
            """
            <ul class="nav-tabs">
                <li class="nav-item"><a href="index.html" class="nav-link $index_active">Summary</a></li>
                <li class="nav-item"><a href="observation.html" class="nav-link $obs_active">Observation</a></li>
                <li class="nav-item"><a href="calibration.html" class="nav-link $cal_active">Calibration</a></li>
                <li class="nav-item"><a href="qa_report.html" class="nav-link $qa_active">QA Report</a></li>
                <li class="nav-item"><a href="plots.html" class="nav-link $plots_active">Plots</a></li>
            </ul>"""
        )

        # Summary page template
        self.templates["summary"] = Template(
            """
            <section class="summary-section">
                <h2>Pipeline Summary</h2>
                <div class="summary-grid">
                    <div class="summary-card">
                        <h3>Project Information</h3>
                        <dl class="info-list">
                            <dt>Project Code:</dt><dd>$project_code</dd>
                            <dt>PI Name:</dt><dd>$pi_name</dd>
                            <dt>SB ID:</dt><dd>$sb_id</dd>
                            <dt>Observation Date:</dt><dd>$observation_date</dd>
                        </dl>
                    </div>
                    <div class="summary-card">
                        <h3>Processing Status</h3>
                        <dl class="info-list">
                            <dt>Overall QA2 Score:</dt><dd class="qa-score qa-$qa_status_class">$qa_score</dd>
                            <dt>Pipeline Version:</dt><dd>$pipeline_version</dd>
                            <dt>CASA Version:</dt><dd>$casa_version</dd>
                            <dt>Processing Date:</dt><dd>$processing_date</dd>
                        </dl>
                    </div>
                    <div class="summary-card">
                        <h3>Data Summary</h3>
                        <dl class="info-list">
                            <dt>Frequency Band:</dt><dd>$frequency_band</dd>
                            <dt>Polarization Mode:</dt><dd>$polarization_mode</dd>
                            <dt>Total Integration:</dt><dd>$total_time</dd>
                            <dt>Number of SPWs:</dt><dd>$num_spws</dd>
                        </dl>
                    </div>
                </div>
            </section>

            <section class="quick-metrics">
                <h2>Quick Metrics</h2>
                <div class="metrics-grid">
                    <div class="metric-card">
                        <span class="metric-value">$total_flagged_percent%</span>
                        <span class="metric-label">Data Flagged</span>
                    </div>
                    <div class="metric-card">
                        <span class="metric-value">$calibrator_count</span>
                        <span class="metric-label">Calibrators</span>
                    </div>
                    <div class="metric-card">
                        <span class="metric-value">$target_count</span>
                        <span class="metric-label">Target Sources</span>
                    </div>
                    <div class="metric-card">
                        <span class="metric-value">$rms_noise</span>
                        <span class="metric-label">RMS Noise (μJy)</span>
                    </div>
                </div>
            </section>"""
        )

        # QA Report template
        self.templates["qa_report"] = Template(
            """
            <section class="qa-section">
                <h2>Quality Assurance Report</h2>
                <div class="qa-overview">
                    <div class="qa-score-display">
                        <span class="qa-badge qa-$overall_qa_class">$overall_qa_score</span>
                        <span class="qa-description">Overall Pipeline Status</span>
                    </div>
                </div>

                <div class="qa-steps">
                    <h3>Processing Steps Status</h3>
                    <div class="qa-grid">$qa_steps_content</div>
                </div>

                $polarization_qa_section

                <div class="qa-notes">
                    <h3>Notes and Recommendations</h3>
                    <div class="note-content">$qa_notes</div>
                </div>
            </section>"""
        )

        # QA step template
        self.templates["qa_step"] = Template(
            """
            <div class="qa-step-card">
                <div class="qa-step-header">
                    <h4>$step_name</h4>
                    <span class="qa-badge qa-$status_class">$status</span>
                </div>
                <p class="qa-step-description">$description</p>
                <div class="qa-step-details">
                    <small>Duration: $duration | Log: <a href="logs/$log_file">$log_file</a></small>
                </div>
            </div>"""
        )

        # Polarization QA section
        self.templates["polarization_qa"] = Template(
            """
            <div class="polarization-qa">
                <h3>Polarization Calibration Status</h3>
                <div class="pol-qa-grid">
                    <div class="pol-qa-card">
                        <h4>Cross-hand Delay (KCROSS)</h4>
                        <span class="qa-badge qa-$kcross_status">$kcross_result</span>
                        <p>Calibrator: $kcross_calibrator</p>
                        <p>Solutions: $kcross_solutions found</p>
                    </div>
                    <div class="pol-qa-card">
                        <h4>D-terms (Df)</h4>
                        <span class="qa-badge qa-$dterms_status">$dterms_result</span>
                        <p>Calibrator: $dterms_calibrator</p>
                        <p>Leakage: $avg_leakage% average</p>
                    </div>
                    <div class="pol-qa-card">
                        <h4>Polarization Models</h4>
                        <span class="qa-badge qa-$polmodel_status">$polmodel_result</span>
                        <p>Sources with models: $pol_sources_count</p>
                        <p>Fractional polarization: $avg_pol_fraction%</p>
                    </div>
                </div>
            </div>"""
        )

        # CSS styles
        self.templates[
            "css"
        ] = """
/* Modern EVLA Pipeline Weblog Styles */
:root {
    --primary-blue: #2c5282;
    --secondary-blue: #3182ce;
    --accent-green: #38a169;
    --warning-orange: #dd6b20;
    --error-red: #e53e3e;
    --background: #f7fafc;
    --surface: #ffffff;
    --text-primary: #2d3748;
    --text-secondary: #4a5568;
    --border-color: #e2e8f0;
    --shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    line-height: 1.6;
    color: var(--text-primary);
    background-color: var(--background);
}

.pipeline-header {
    background: linear-gradient(135deg, var(--primary-blue), var(--secondary-blue));
    color: white;
    padding: 1rem 2rem;
    box-shadow: var(--shadow);
}

.pipeline-header h1 {
    font-size: 1.75rem;
    font-weight: 600;
    margin-bottom: 0.5rem;
}

.main-nav {
    margin-top: 1rem;
}

.nav-tabs {
    display: flex;
    list-style: none;
    gap: 0.25rem;
}

.nav-item {
    border-radius: 0.375rem 0.375rem 0 0;
}

.nav-link {
    display: block;
    padding: 0.5rem 1rem;
    color: rgba(255, 255, 255, 0.8);
    text-decoration: none;
    border-radius: 0.375rem 0.375rem 0 0;
    transition: all 0.2s;
}

.nav-link:hover, .nav-link.active {
    background-color: var(--surface);
    color: var(--text-primary);
}

.content {
    max-width: 1200px;
    margin: 0 auto;
    padding: 2rem;
}

.summary-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    gap: 1.5rem;
    margin-top: 1.5rem;
}

.summary-card, .qa-step-card, .pol-qa-card {
    background: var(--surface);
    border-radius: 0.5rem;
    padding: 1.5rem;
    box-shadow: var(--shadow);
    border: 1px solid var(--border-color);
}

.summary-card h3, .qa-step-card h4, .pol-qa-card h4 {
    color: var(--primary-blue);
    margin-bottom: 1rem;
    font-size: 1.125rem;
    font-weight: 600;
}

.info-list {
    display: grid;
    gap: 0.5rem;
}

.info-list dt {
    font-weight: 500;
    color: var(--text-secondary);
}

.info-list dd {
    font-weight: 400;
}

.metrics-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
    gap: 1rem;
    margin-top: 1.5rem;
}

.metric-card {
    text-align: center;
    background: var(--surface);
    border-radius: 0.5rem;
    padding: 1.5rem;
    box-shadow: var(--shadow);
}

.metric-value {
    display: block;
    font-size: 2rem;
    font-weight: 600;
    color: var(--primary-blue);
}

.metric-label {
    display: block;
    font-size: 0.875rem;
    color: var(--text-secondary);
    margin-top: 0.25rem;
}

.qa-badge {
    display: inline-block;
    padding: 0.25rem 0.75rem;
    border-radius: 9999px;
    font-size: 0.875rem;
    font-weight: 500;
    text-transform: uppercase;
}

.qa-pass { background-color: #c6f6d5; color: #22543d; }
.qa-partial { background-color: #fed7aa; color: #9c4221; }
.qa-fail { background-color: #fed7d7; color: #742a2a; }
.qa-unknown { background-color: #e2e8f0; color: var(--text-secondary); }

.qa-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    gap: 1rem;
    margin-top: 1rem;
}

.qa-step-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 0.5rem;
}

.pol-qa-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
    gap: 1rem;
    margin-top: 1rem;
}

.pipeline-footer {
    background: var(--text-secondary);
    color: white;
    text-align: center;
    padding: 1rem;
    margin-top: 2rem;
    font-size: 0.875rem;
}

/* Responsive design */
@media (max-width: 768px) {
    .nav-tabs {
        flex-direction: column;
    }

    .content {
        padding: 1rem;
    }

    .summary-grid,
    .metrics-grid,
    .qa-grid,
    .pol-qa-grid {
        grid-template-columns: 1fr;
    }
}
"""

        # Basic JavaScript for interactivity
        self.templates[
            "js"
        ] = """
// Modern EVLA Pipeline Weblog JavaScript
document.addEventListener('DOMContentLoaded', function() {
    // Add active class to current page nav link
    const currentPage = window.location.pathname.split('/').pop() || 'index.html';
    const navLinks = document.querySelectorAll('.nav-link');
    navLinks.forEach(link => {
        if (link.getAttribute('href') === currentPage) {
            link.classList.add('active');
        }
    });

    // Add click animations to cards
    const cards = document.querySelectorAll('.summary-card, .qa-step-card, .pol-qa-card, .metric-card');
    cards.forEach(card => {
        card.addEventListener('click', function() {
            this.style.transform = 'scale(0.98)';
            setTimeout(() => {
                this.style.transform = 'scale(1)';
            }, 150);
        });
    });

    // Collapsible sections
    const collapsibles = document.querySelectorAll('[data-collapsible]');
    collapsibles.forEach(element => {
        element.addEventListener('click', function() {
            const target = document.querySelector(this.getAttribute('data-target'));
            if (target) {
                target.style.display = target.style.display === 'none' ? 'block' : 'none';
            }
        });
    });
});
"""

    def render_template(self, template_name: str, context: Dict[str, Any]) -> str:
        """Render a template with the given context."""
        if template_name not in self.templates:
            raise ValueError(f"Template '{template_name}' not found")

        template = self.templates[template_name]
        try:
            return template.safe_substitute(**context)
        except KeyError:
            # For missing variables, substitute with empty string
            return template.safe_substitute(**context)

    def generate_full_page(
        self,
        page_title: str,
        content_template: str,
        context: Dict[str, Any],
        active_nav: str = "",
    ) -> str:
        """Generate a complete HTML page."""

        # Prepare navigation context
        nav_context = {
            "index_active": "active" if active_nav == "index" else "",
            "obs_active": "active" if active_nav == "observation" else "",
            "cal_active": "active" if active_nav == "calibration" else "",
            "qa_active": "active" if active_nav == "qa" else "",
            "plots_active": "active" if active_nav == "plots" else "",
        }

        # Render navigation
        navigation = self.render_template("navigation", nav_context)

        # Render main content
        content = self.render_template(content_template, context)

        # Render full page
        page_context = {
            "title": page_title,
            "navigation": navigation,
            "content": content,
            "css_content": self.templates["css"],
            "js_content": self.templates["js"],
            "pipeline_version": context.get("pipeline_version", "Unknown"),
            "generation_date": datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC"),
        }

        return self.render_template("base", page_context)


def create_weblog_generator():
    """Factory function to create weblog generator."""
    return WeblogTemplateEngine()
